name: Add Reviewers to PR

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers
        uses: ahmadnassri/action-auto-request-review@v1
        with:
          reviewers: sally0226, J-Hoplin, chsjen492, Choi-JY1107
